# File to store metadata about publication (name, affiliation, etc.)
metadata: metadata.yml
# File storing requirements for publication note (pandas, seaborn etc for python notebooks)
reqs: requirements.txt
# File name for executed file in publication. This file will be used for DOI .upload 
executed_file: executed_notebook.ipynb
# Extension for note publication notebook
note_file_ext: .ipynb
# Script to execute. This command will be run with 2 arguments: $<path/to/publication/note> $<path/to/publication/executed_file>
execute_note: run_note.sh
# command line to install requirements of publications. This command will be run with arguments: $<path/to/publication $<path/to/publication/requirements.txt>
install_requirements: install_reqs.sh